Import Library

In [ ]:
import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import matplotlib.ticker as ticker
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

Import Dataset

In [ ]:
df = pd.read_csv('indian_liver_patient.csv')
df.head()

Age  Gender  Total_Bilirubin  ...  Albumin  Albumin_and_Globulin_Ratio  Dataset
0   65       0              0.7  ...      3.3                        0.90        1
1   62       1             10.9  ...      3.2                        0.74        1
2   62       1              7.3  ...      3.3                        0.89        1
3   58       1              1.0  ...      3.4                        1.00        1
4   72       1              3.9  ...      2.4                        0.40        1

[5 rows x 11 columns]

Melihat Jumlah Dataset hanya kolom Dataset dan Jumlah Masing masing kelas

In [ ]:
df['Dataset'].value_counts()

1    414
2    165
Name: Dataset, dtype: int64

Melihat Kolom yang ada pada Dataset

In [ ]:
df.columns

Index(['Age', 'Gender', 'Total_Bilirubin', 'Direct_Bilirubin',
       'Alkaline_Phosphotase', 'Alamine_Aminotransferase',
       'Aspartate_Aminotransferase', 'Total_Protiens', 'Albumin',
       'Albumin_and_Globulin_Ratio', 'Dataset'],
      dtype='object')

Proses merubah Pandas data frame menjadi Numpy menggunakan scikit-learn library

In [ ]:
X = df[['Age', 'Gender', 'Total_Bilirubin', 'Direct_Bilirubin',
       'Alkaline_Phosphotase', 'Alamine_Aminotransferase',
       'Aspartate_Aminotransferase', 'Total_Protiens', 'Albumin',
       'Albumin_and_Globulin_Ratio']] .values  #.astype(float)
X[0:5]

array([[6.50e+01, 0.00e+00, 7.00e-01, 1.00e-01, 1.87e+02, 1.60e+01,
        1.80e+01, 6.80e+00, 3.30e+00, 9.00e-01],
       [6.20e+01, 1.00e+00, 1.09e+01, 5.50e+00, 6.99e+02, 6.40e+01,
        1.00e+02, 7.50e+00, 3.20e+00, 7.40e-01],
       [6.20e+01, 1.00e+00, 7.30e+00, 4.10e+00, 4.90e+02, 6.00e+01,
        6.80e+01, 7.00e+00, 3.30e+00, 8.90e-01],
       [5.80e+01, 1.00e+00, 1.00e+00, 4.00e-01, 1.82e+02, 1.40e+01,
        2.00e+01, 6.80e+00, 3.40e+00, 1.00e+00],
       [7.20e+01, 1.00e+00, 3.90e+00, 2.00e+00, 1.95e+02, 2.70e+01,
        5.90e+01, 7.30e+00, 2.40e+00, 4.00e-01]])

In [ ]:
y = df['Dataset'].values
y[0:5]

array([1, 1, 1, 1, 1])

Normalisasi Data

In [ ]:
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:5]

array([[ 1.24740264, -1.77079482, -0.42031984, -0.49541415, -0.42887006,
        -0.35583241, -0.31911128,  0.29372174,  0.20344649, -0.14738974],
       [ 1.06230624,  0.56471817,  1.21893587,  1.42351783,  1.67508295,
        -0.09357256, -0.03596174,  0.93965456,  0.07746198, -0.64846078],
       [ 1.06230624,  0.56471817,  0.64037503,  0.92601694,  0.81624275,
        -0.11542755, -0.14645913,  0.47827397,  0.20344649, -0.17870668],
       [ 0.81551105,  0.56471817, -0.37210644, -0.38880682, -0.44941648,
        -0.3667599 , -0.3122052 ,  0.29372174,  0.329431  ,  0.16577966],
       [ 1.67929422,  0.56471817,  0.09395646,  0.17976562, -0.3959958 ,
        -0.29573119, -0.17753651,  0.75510233, -0.9304141 , -1.71323673]])

Memisahkan Data Training dan Data Testing

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (463, 10) (463,)
Test set: (116, 10) (116,)


# Penerapan KNN

Fase Training

In [ ]:
k = 5
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

Fase Testing

In [ ]:
yhat = neigh.predict(X_test)
yhat[0:50]

array([2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1,
       2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2,
       1, 1, 2, 1, 1, 1])

Menghitung Akurasi 

In [ ]:
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  0.7883369330453563
Test set Accuracy:  0.6896551724137931
